sets.exported = {
    item="SP Gobbie Key",
    head="Abyssal Mask",
    item="Voidhand: BLU",
    item="S. Astral Detritus",
    item="Sanjaku-Tenugui",
    item="Shinobi-Tabi",
    item="Toolbag (Shihe)",
    item="Toolbag (Moku)",
    item="Toolbag (Ino)",
    item="Toolbag (Shika)",
    item="Toolbag (Cho)",
    item="Inoshishinofuda",
    item="Durium Sheet",
    item="L. Wing Box",
    item="Mokujin",
    item="Shikanofuda",
    item="S. Kindred Crest",
    item="Maliya. Coral",
    item="Kindred's Crest",
    item="Rem's Tale Ch.6",
    item="Rem's Tale Ch.9",
    item="Riftborn Boulder",
    item="Rem's Tale Ch.8",
    item="Pluton",
    item="Pluton Case",
    item="P. NIN Card",
    item="Copper Voucher",
    item="H. Kindred Crest",
    item="Rusted I. Card",
    item="P. WHM Card",
    item="P. BLU Card",
    item="Raxa",
    item="Linkpearl",
    item="Frayed Sack (Pel)",
    item="Frayed Sack (Tau)",
    item="Earth Cluster",
    item="Pellucid Stone",
    item="Fern Stone",
    item="Malboro Fiber",
    item="Taupe Stone",
    item="Frayed Sack (Fer)",
    item="Red Curry Bun",
    item="Lustreless Hide",
    item="Rem's Tale Ch.7",
    item="Lightning Cluster",
    item="Voidsnapper",
    item="Boulder Case",
    item="Mars Orb",
    item="Silver Voucher",
    item="Wind Cluster",
    item="Water Cluster",
    item="Void Grass",
    item="Fire Cluster",
    item="Void Crystal",
    item="Dark Cluster",
    item="Grape Daifuku",
    item="Chonofuda",
    item="Ice Cluster",
    item="Gil",
    item="Imperial Standard",
    item="Fire Crystal",
    item="Bahut",
    main="Girru",
    item="Lustreless Wing",
    item="Jeunoan Flag",
    item="Noble's Bed",
    item="Herb Seeds",
    item="Tumult's Blood",
    item="Plovid Effluvium",
    item="Bahut",
    item="Macuil Horn",
    item="Bahut",
    item="Ethereal Incense",
    item="Joyous's Moss",
    item="Macuil Plating",
    item="Joyous's Moss",
    item="Ayapec's Shell",
    hands="Fsh. Gloves",
    legs="Angler's Hose",
    feet="Fisherman's Boots",
    item="Bahut",
    item="Ayapec's Shell",
    item="Defiant Sweat",
    item="Lustreless Hide",
    item="Lustreless Scale",
    item="Bahut",
    item="Bahut",
    item="Lustreless Scale",
    item="Oxblood",
    item="Beetle Blood",
    item="Phoenix Feather",
    item="Lustreless Wing",
    item="Bastokan Flag",
    item="L. Jadeshell",
    item="Vana'clock",
    item="M. Silverpiece",
    item="Heroism Crystal",
    item="S. Astral Detritus",
    item="Ceramic Flowerpot",
    item="Bahut",
    item="Bahut",
    item="Beitetsu Box",
    item="Boulder Case",
    item="Pluton Case",
    item="Beitetsu Parcel",
    item="Bahut",
    item="Beitetsu",
    item="Alexandrite",
    item="Riftsand",
    item="Bahut",
    left_ring="Trizek Ring",
    item="Hvy. Metal Pouch",
    item="Pluton",
    item="Handshard: WHM",
    item="100 Byne Bill",
    item="Heavy Metal",
    item="Wailing Stone +2",
    item="Headshard: RNG",
    item="Torsoshard: BLU",
    item="Handshard: BLU",
    item="Footshard: BLU",
    item="Voidtorso: BLU",
    item="Voidhead: BLU",
    item="Voidhand: BLU",
    item="Windurstian Flag",
    item="Voidfoot: BLU",
    body={ name="Cab. Surcoat +1", augments={'Enhances "Fealty" effect',}},
    body={ name="Sakpata's Plate", augments={'Path: A',}},
    body="Rev. Surcoat +2",
    head={ name="Yorium Barbuta", augments={'DEF+25','Spell interruption rate down -10%','Phalanx +3',}},
    head={ name="Souv. Schaller +1", augments={'HP+105','Enmity+9','Potency of "Cure" effect received +15%',}},
    head={ name="Cab. Coronet +1", augments={'Enhances "Iron Will" effect',}},
    head={ name="Loess Barbuta +1", augments={'Path: A',}},
    sub="Aegis",
    head="Sakpata's Helm",
    hands={ name="Vitiation Gloves", augments={'Enhancing Magic duration',}},
    body="Atrophy Tabard +1",
    body="Lethargy Sayon +1",
    body={ name="Vitiation Tabard", augments={'Enhances "Chainspell" effect',}},
    head="Atro. Chapeau +1",
    head="Leth. Chappel +1",
    head={ name="Viti. Chapeau +1", augments={'Enfeebling Magic duration','Magic Accuracy',}},
    hands="Atrophy Gloves +1",
    hands="Leth. Gantherots +1",
    back={ name="Ghostfyre Cape", augments={'Enfb.mag. skill +6','Enha.mag. skill +7','Mag. Acc.+7','Enh. Mag. eff. dur. +20',}},
    back={ name="Sucellos's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','Mag. Acc.+10','"Fast Cast"+10','Damage taken-5%',}},
    feet="Atrophy Boots +1",
    feet="Leth. Houseaux +1",
    feet={ name="Vitiation Boots +1", augments={'Immunobreak Chance',}},
    legs="Atrophy Tights +1",
    legs="Leth. Fuseau +1",
    legs={ name="Vitiation Tights", augments={'Enspell Damage','Accuracy',}},
    sub="Oneiros Knife",
    back={ name="Weard Mantle", augments={'VIT+3','DEX+3','Enmity+4','Phalanx +5',}},
    back={ name="Rudianos's Mantle", augments={'HP+60','Eva.+20 /Mag. Eva.+20','Mag. Evasion+10','"Cure" potency +10%','Phys. dmg. taken-10%',}},
    back={ name="Rudianos's Mantle", augments={'HP+60','Eva.+20 /Mag. Eva.+20','Mag. Evasion+10','"Fast Cast"+10','Phys. dmg. taken-10%',}},
    back={ name="Rudianos's Mantle", augments={'HP+60','Eva.+20 /Mag. Eva.+20','Mag. Evasion+10','Enmity+10','Chance of successful block +5',}},
    waist="Creed Baudrier",
    waist="Asklepian Belt",
    neck="Sacro Gorget",
    feet={ name="Founder's Greaves", augments={'VIT+7','Accuracy+8','Mag. Evasion+12',}},
    feet={ name="Odyssean Greaves", augments={'Accuracy+22','"Fast Cast"+5','VIT+10',}},
    feet={ name="Eschite Greaves", augments={'HP+80','Enmity+7','Phys. dmg. taken -4',}},
    feet={ name="Souveran Schuhs +1", augments={'HP+105','Enmity+9','Potency of "Cure" effect received +15%',}},
    feet={ name="Cab. Leggings +1", augments={'Enhances "Guardian" effect',}},
    feet="Sakpata's Leggings",
    legs={ name="Founder's Hose", augments={'MND+5','Mag. Acc.+13',}},
    legs={ name="Souv. Diechlings +1", augments={'HP+105','Enmity+9','Potency of "Cure" effect received +15%',}},
    legs={ name="Cab. Breeches +1", augments={'Enhances "Invincible" effect',}},
    legs="Sakpata's Cuisses",
    hands={ name="Souv. Handsch. +1", augments={'HP+105','Enmity+9','Potency of "Cure" effect received +15%',}},
    hands={ name="Cab. Gauntlets +1", augments={'Enhances "Chivalry" effect',}},
    hands="Sakpata's Gauntlets",
    body="Shab. Cuirass +1",
    body={ name="Yorium Cuirass", augments={'DEF+25','Spell interruption rate down -10%','Phalanx +3',}},
    body={ name="Souv. Cuirass +1", augments={'HP+105','Enmity+9','Potency of "Cure" effect received +15%',}},
    item="Lucid Potion I",
    item="Lucid Ether I",
    item="Healing Salve I",
    item="Clear Salve I",
    item="Instant Reraise",
    item="Assassin's Drink",
    item="Fighter's Drink",
    item="Gnostic's Drink",
    item="Spy's Drink",
    item="Champion's Drink",
    item="Lucid Potion II",
    item="Lucid Ether II",
    item="Megalixir",
    item="Lucid Wings I",
    item="Catholicon",
    item="Braver's Drink",
    item="Sprinter's Drink",
    item="Soldier's Drink",
    item="Healing Salve II",
    item="Clear Salve II",
    item="Monarch's Drink",
    item="Barbarian's Drink",
    item="Oracle's Drink",
    item="Lucid Potion III",
    item="Lucid Ether III",
    item="Lucid Elixir I",
    item="Daedalus Wing",
    item="Savior's Tonic",
    item="Mirror's Tonic",
    item="Moneta's Tonic",
    item="Cleric's Drink",
    item="Steadfast Tonic",
    item="Healing Powder",
    item="Mana Powder",
    item="Catholicon +1",
    item="Poison Buffer",
    item="Healing Mist",
    item="Mana Mist",
    item="Vicar's Drink",
    item="Lucid Elixir II",
    item="Dusty Reraise",
    item="Primeval Brew",
    item="Lucid Wings II",
    item="Charm Buffer",
    item="Curse Buffer",
    item="A. Tok.: Head +1",
    back={ name="Bookworm's Cape", augments={'INT+3','MND+1','Helix eff. dur. +20',}},
    item="A. Vou.: Fingers",
    item="A. Tok.: Legs +1",
    item="A. Tok.: Body +1",
    body="Fsh. Tunica",
    item="Imp. Slv. Piece",
    item="A. Tok.: Hands +1",
    item="A. Tok.: Fingers",
    back="Aptitude Mantle +1",
    item="A. Tok.: Feet +1",
    item="Tumult's Blood",
    item="A. Vou.: Feet +1",
    item="A. Vou.: Body +1",
    item="A. Vou.: Legs +1",
    item="A. Vou.: Head +1",
    sub={ name="Schiavona", augments={'Attack+3',}},
    sub="Malignance Sword",
    item="A. Vou.: Hands +1",
    item="Tumult's Blood",
    item="Sarameya's Hide",
    item="Abdhaljs Dust",
    item="Abdhaljs Sap",
    item="O. Bronzepiece",
    item="1 Byne Bill",
    item="T. Whiteshell",
    item="Abdhaljs Thread",
    left_ring="Tavnazian Ring",
    back="Anchoret's Mantle",
    item="100 Byne Bill",
    hands="Helios Gloves",
    item="Abdhaljs Fiber",
    feet="Helios Boots",
    legs="Telchine Braconi",
    legs="Telchine Braconi",
    head="Helios Band",
    body="Taeon Tabard",
    item="Abdhaljs Metal",
    hands="Telchine Gloves",
    item="Abdhaljs Resin",
    head={ name="Jumalik Helm", augments={'MND+10','"Mag.Atk.Bns."+15','Magic burst dmg.+10%','"Refresh"+1',}},
    feet="Yorium Sabatons",
    item="A. Voucher: Weapon",
    item="A. Voucher: Back",
    item="Abdhaljs Dust",
    item="P. BLM Card",
    main={ name="Ferocity", augments={'STR+10','VIT+10','"Dbl.Atk."+3','DMG:+15',}},
    item="Bukhis's Wing",
    back="Cichol's Mantle",
    item="Eikondrite",
    left_ear={ name="Azimuth Earring +1", augments={'System: 1 ID: 1676 Val: 0','Mag. Acc.+11','Damage taken-3%',}},
    left_ear={ name="Hattori Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+11','Mag. Acc.+11','"Store TP"+3',}},
    item="Behemoth Steak",
    item="Mog Pell (Red)",
    left_ear={ name="Skulk. Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+11','Mag. Acc.+11','"Store TP"+3',}},
    left_ear={ name="Leth. Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+13','Mag. Acc.+13','"Dbl.Atk."+4',}},
    item="Abdhaljs Matter",
    item="Abdhaljs Dye",
    item="P. GEO Card",
    item="P. RNG Card",
    item="Abdhaljs Thread",
    item="P. THF Card",
    item="P. SCH Card",
    item="P. DRK Card",
    item="P. BLU Card",
    main="Router",
    item="Mog Pell (Silver)",
    item="Pulchridopt Wing",
    item="Bonanza Pearl",
    item="Bonanza Pearl",
    item="P. BLU Card",
    item="P. COR Card",
    item="P. DRG Card",
    item="P. WHM Card",
    item="P. WAR Card",
    item="Refractive Crystal",
    item="Coca's Wing",
    item="Ashweed",
    item="Voidsnapper",
    item="Void Crystal",
    item="Lustreless Wing",
    item="Lustreless Scale",
    item="Fu's Scale",
    item="Kin's Scale",
    item="Kei's Scale",
    item="Maze Tabula M01",
    item="Gin's Scale",
    item="Sublime Sushi +1",
    item="Beetle Blood",
    item="Kyou's Scale",
    item="Copper Voucher",
    item="Fern Stone",
    item="Abdhaljs Seal",
    item="Moogle Amp.",
    item="Tropical Crepe",
    item="S. Kindred Crest",
    item="Holy Water",
    item="Trump Card",
    item="Antacid",
    item="Octahedrite",
    item="Panacea",
    item="Mog Pell (Red)",
    item="Grape Daifuku",
    item="Kupon I-Seal",
    item="Holy Water",
    item="Oxblood",
    item="Sublime Sushi",
    item="Remedy",
    item="Poison Potion",
    item="Hi-Reraiser",
    item="Frayed Sack (Fer)",
    item="SP Gobbie Key",
    item="Trump Card Case",
    item="Holy Water",
    item="Iron Plate",
    item="L. Wing Box",
    item="Om. Sandwich",
    item="Silver Voucher",
    item="Kindred's Crest",
    item="Old Case",
    item="Ra'Kaz. Starstone",
    item="Colorless Soul",
    item="Ra'Kaz. Sapphire",
    item="Lustreless Wing",
    item="H. Kindred Crest",
    item="Dec. Bul. Pouch",
    item="Miso Ramen",
    item="Kindred's Seal",
    item="Beastmen's Seal",
    item="Phil. Stone",
    item="Storage Slip 02",
    item="Storage Slip 13",
    item="Storage Slip 22",
    item="Storage Slip 18",
    item="Storage Slip 04",
    body="Odyss. Chestplate",
    left_ear={ name="Beck. Earring +1", augments={'System: 1 ID: 1676 Val: 0','Pet: Accuracy+15 Pet: Rng. Acc.+15','Pet: Mag. Acc.+15','Damage taken-5%',}},
    item="Storage Slip 03",
    range="Matre Bell",
    body="Fisherman's Smock",
    item="Storage Slip 06",
    item="Storage Slip 28",
    item="Storage Slip 09",
    item="Storage Slip 07",
    item="Storage Slip 16",
    item="Storage Slip 08",
    item="Storage Slip 23",
    item="Abdhaljs Anima",
    item="Genbu Scrap",
    item="Storage Slip 11",
    item="Abdhaljs Gem",
    item="Storage Slip 19",
    item="Abdhaljs Nugget",
    ammo="Date Shuriken",
    ammo="Fly Lure",
    ammo="Meatball",
    legs={ name="Enticer's Pants", augments={'MP+50','Pet: Accuracy+15 Pet: Rng. Acc.+15','Pet: Mag. Acc.+15','Pet: Damage taken -5%',}},
    ammo="Pet Food Theta",
    item="Abdhaljs Matter",
    item="Storage Slip 01",
    item="Storage Slip 05",
    item="Storage Slip 10",
    head={ name="Vanya Hood", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    ammo="Quartz Tathlum +1",
    feet={ name="Vanya Clogs", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    left_ear="Meili Earring",
    feet={ name="Nyame Sollerets", augments={'Path: B',}},
    legs="Mummu Kecks +2",
    legs={ name="Nyame Flanchard", augments={'Path: B',}},
    hands={ name="Nyame Gauntlets", augments={'Path: B',}},
    neck="Fotia Gorget",
    range="Lu Shang's F. Rod",
    waist="Fotia Belt",
    left_ear="Telos Earring",
    ammo="Yetshila +1",
    body={ name="Nyame Mail", augments={'Path: B',}},
    sub="Naegling",
    sub={ name="Thibron", augments={'TP Bonus +1000',}},
    head="Befouled Crown",
    sub="Tauret",
    feet={ name="Psycloth Boots", augments={'MP+50','INT+7','"Conserve MP"+6',}},
    head="Shobuhouou Kabuto",
    main={ name="Marin Staff +1", augments={'Path: A',}},
    body={ name="Vanya Robe", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    legs={ name="Vanya Slops", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    waist={ name="Shinjutsu-no-Obi +1", augments={'Path: A',}},
    hands={ name="Vanya Cuffs", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    body="Ken. Samue +1",
    waist="Gishdubar Sash",
    legs="Perdition Slops",
    back={ name="Andartia's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','"Store TP"+10',}},
    sub="Chanter's Shield",
    neck="Dualism Collar +1",
    ammo="Strobilus",
    head={ name="Dampening Tam", augments={'DEX+10','Accuracy+15','Mag. Acc.+15','Quadruple Attack +3',}},
    hands={ name="Otomi Gloves", augments={'HP+30','MP+30','MP+30',}},
    left_ear="Beatific Earring",
    sub={ name="Centovente", augments={'TP Bonus +1000',}},
    body={ name="Weather. Robe +1", augments={'MP+120',}},
    ammo="Sroda Tathlum",
    back={ name="Andartia's Mantle", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','Mag. Acc.+10','"Fast Cast"+10','Damage taken-5%',}},
    neck="Saevus Pendant +1",
    head="Gleti's Mask",
    head={ name="Adhemar Bonnet +1", augments={'STR+12','DEX+12','Attack+20',}},
    hands={ name="Adhemar Wrist. +1", augments={'DEX+12','AGI+12','Accuracy+20',}},
    ammo="Date Shuriken",
    body="Malignance Tabard",
    head={ name="Nyame Helm", augments={'Path: B',}},
    legs="Mou. Seraweels +1",
    body={ name="Adhemar Jacket +1", augments={'DEX+12','AGI+12','Accuracy+20',}},
    body="Passion Jacket",
    left_ear="Eabani Earring",
    ammo="Voluspa Tathlum",
    body="Oshosi Vest +1",
    left_ring="Hajduk Ring +1",
    hands="Meg. Gloves +2",
    hands="Mummu Wrists +2",
    hands={ name="Rawhide Gloves", augments={'Mag. Acc.+15','INT+7','MND+7',}},
    back={ name="Andartia's Mantle", augments={'AGI+20','Eva.+20 /Mag. Eva.+20','Evasion+10','"Dual Wield"+10','Evasion+15',}},
    hands={ name="Gazu Bracelets +1", augments={'Path: A',}},
    legs="Malignance Tights",
    legs="Gleti's Breeches",
    waist="Svelt. Gouriz +1",
    left_ear="Sherida Earring",
    sub={ name="Bunzi's Rod", augments={'Path: A',}},
    left_ring="Shneddick Ring +1",
    feet="Gleti's Boots",
    left_ring="Defending Ring",
    feet="Mummu Gamash. +2",
    range="Armageddon",
    feet={ name="Herculean Boots", augments={'Accuracy+29','"Triple Atk."+4','AGI+3','Attack+6',}},
    neck="Magoraga Beads",
    neck="Erudit. Necklace",
    waist={ name="Sailfi Belt +1", augments={'Path: A',}},
    waist="Chaac Belt",
    left_ear="Evans Earring",
    left_ring="Gere Ring",
    left_ring="Epona's Ring",
    body={ name="Tatena. Harama. +1", augments={'Path: A',}},
    left_ring="Dingir Ring",
    sub={ name="Gada", augments={'Enh. Mag. eff. dur. +5','VIT+7','"Mag.Atk.Bns."+8',}},
    ammo="Egoist's Tathlum",
    feet={ name="Carmine Greaves +1", augments={'HP+80','MP+80','Phys. dmg. taken -4',}},
    legs={ name="Psycloth Lappas", augments={'MP+80','Mag. Acc.+15','"Fast Cast"+7',}},
    body={ name="Kaykaus Bliaut +1", augments={'MP+80','"Cure" potency +6%','"Conserve MP"+7',}},
    left_ear="Etiolation Earring",
    main="Chatoyant Staff",
    ammo="Pemphredo Tathlum",
    ammo="Per. Lucky Egg",
    sub="Culminus",
    hands="Aya. Manopolas +1",
    head="Bunzi's Hat",
    head="Aya. Zucchetto +2",
    head="Mall. Chapeau +2",
    legs="Aya. Cosciales +2",
    body="Bunzi's Robe",
    body="Inyanga Jubbah +2",
    body="Ayanmo Corazza +2",
    waist="Oneiros Rope",
    waist="Plat. Mog. Belt",
    legs="Inyanga Shalwar +2",
    head="Inyanga Tiara +2",
    hands="Inyan. Dastanas +2",
    feet="Inyan. Crackows +2",
    hands={ name="Kaykaus Cuffs +1", augments={'MP+80','MND+12','Mag. Acc.+20',}},
    waist="Luminary Sash",
    legs="Bunzi's Pants",
    legs={ name="Amalric Slops +1", augments={'MP+80','Mag. Acc.+20','"Mag.Atk.Bns."+20',}},
    left_ring="Regal Ring",
    feet="Navon Crackows",
    hands={ name="Gende. Gages +1", augments={'Phys. dmg. taken -3%','Magic dmg. taken -2%','Song spellcasting time -5%',}},
    feet="Crier's Gaiters",
    neck="Lissome Necklace",
    neck="Incanter's Torque",
    head={ name="Kaykaus Mitra +1", augments={'MP+80','MND+12','Mag. Acc.+20',}},
    waist="Hachirin-no-Obi",
    left_ring="Eihwaz Ring",
    waist="K. Kachina Belt +1",
    waist="Ioskeha Belt +1",
    feet="Regal Pumps +1",
    body="Mou. Manteel +1",
    feet={ name="Kaykaus Boots +1", augments={'MP+80','MND+12','Mag. Acc.+20',}},
    head="Mousai Turban +1",
    left_ear="Trux Earring",
    left_ear="Sanare Earring",
    left_ear="Crematio Earring",
    range="Blurred Harp +1",
    left_ear="Magnetic Earring",
    legs={ name="Kaykaus Tights +1", augments={'MP+80','MND+12','Mag. Acc.+20',}},
    left_ear="Musical Earring",
    back={ name="Aurist's Cape +1", augments={'Path: A',}},
    hands="Mousai Gages +1",
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    neck="Mnbw. Whistle +1",
    head={ name="Amalric Coif +1", augments={'MP+80','Mag. Acc.+20','"Mag.Atk.Bns."+20',}},
    body={ name="Cohort Cloak +1", augments={'Path: A',}},
    waist="Kasiri Belt",
    left_ring="Kishar Ring",
    waist="Cornelia's Belt",
    hands="Jhakri Cuffs +2",
    body={ name="Amalric Doublet +1", augments={'MP+80','Mag. Acc.+20','"Mag.Atk.Bns."+20',}},
    left_ring="Mallquis Ring",
    left_ring="Freke Ring",
    sub="Irenic Strap +1",
    left_ring="Archon Ring",
    legs="Shedir Seraweels",
    feet={ name="Amalric Nails +1", augments={'Mag. Acc.+20','"Mag.Atk.Bns."+20','"Conserve MP"+7',}},
    legs="Assid. Pants +1",
    waist="Chuq'aba Belt",
    legs="Doyen Pants",
    left_ear="Mache Earring +1",
    back="Fi Follet Cape +1",
    hands={ name="Amalric Gages +1", augments={'INT+12','Mag. Acc.+20','"Mag.Atk.Bns."+20',}},
    left_ring="Mephitas's Ring",
    legs={ name="Chironic Hose", augments={'Mag. Acc.+29','Spell interruption rate down -6%','MND+10',}},
    head={ name="Carmine Mask +1", augments={'Accuracy+20','Mag. Acc.+12','"Fast Cast"+4',}},
    body="Vrikodara Jupon",
    neck="Reti Pendant",
    legs={ name="Chironic Hose", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','"Fast Cast"+3','INT+8','Mag. Acc.+11','"Mag.Atk.Bns."+14',}},
    sub="Thuellaic Ecu +1",
    left_ear="Mimir Earring",
    ammo="Oshasha's Treatise",
    waist={ name="Kentarch Belt +1", augments={'Path: A',}},
    neck={ name="Loricate Torque +1", augments={'Path: A',}},
    sub="Enki Strap",
    ammo="Decimating Bullet",
    sub="Maxentius",
    waist="Grunfeld Rope",
    neck="Nodens Gorget",
    left_ring={ name="Mephitas's Ring +1", augments={'Path: A',}},
    left_ear="Glorious Earring",
    left_ring="Eshmun's Ring",
    left_ear="Nourish. Earring +1",
    left_ring="Dim. Ring (Dem)",
    main="Malignance Pole",
    waist="Eschan Stone",
    left_ring="Dim. Ring (Holla)",
    ammo="Living Bullet",
    ammo="Decimating Bullet",
    left_ring="Inyanga Ring",
    left_ring="Rufescent Ring",
    ammo="Living Bullet",
    neck="Debilis Medallion",
    waist="Carrier's Sash",
    waist="Olympus Sash",
    ammo={ name="Ghastly Tathlum +1", augments={'Path: A',}},
    left_ear="Reraise Earring",
    left_ring="Menelaus's Ring",
    left_ring="Haoma's Ring",
    ammo="Sapience Orb",
    sub="Clerisy Strap +1",
    left_ring="Mujin Band",
    ammo="Homiliary",
    sub="Ammurapi Shield",
    sub={ name="Colada", augments={'Enh. Mag. eff. dur. +3','Mag. Acc.+17','"Mag.Atk.Bns."+2',}},
    feet={ name="Herculean Boots", augments={'"Fast Cast"+6','MND+3','"Mag.Atk.Bns."+2',}},
    left_ear="Mache Earring +1",
    left_ring="Chirich Ring +1",
    neck="Baetyl Pendant",
    left_ear="Malignance Earring",
    legs={ name="Herculean Trousers", augments={'Accuracy+22','"Fast Cast"+6','"Mag.Atk.Bns."+12',}},
    neck="Peacock Charm",
    neck="Combatant's Torque",
    left_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
    hands={ name="Herculean Gloves", augments={'Accuracy+16','"Fast Cast"+6','VIT+5','Mag. Acc.+3','"Mag.Atk.Bns."+10',}},
    ammo="Hydrocera",
    left_ear="Ishvara Earring",
    neck="Warder's Charm +1",
    left_ear="Thrud Earring",
    left_ear="Dedition Earring",
    left_ring="Shukuyu Ring",
    left_ring="Evanescence Ring",
    ammo="Seraphic Ampulla",
    back="Swith Cape +1",
    left_ear="Cessance Earring",
    back="Twilight Cape",
    left_ear="Crep. Earring",
    left_ring="Lebeche Ring",
    left_ear="Mendi. Earring",
    ammo="Falcon Eye",
    left_ring="Mummu Ring",
    left_ear="Odr Earring",
    neck="Orunmila's Torque",
    left_ring="Begrudging Ring",
    waist="Siegel Sash",
    left_ring="Ilabrat Ring",
    back="Moonlight Cape",
    left_ear="Suppanomimi",
    left_ear="Brutal Earring",
    left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    left_ear="Barkaro. Earring",
    left_ear={ name="Lugra Earring +1", augments={'Path: A',}},
    left_ear="Loquac. Earring",
    left_ring="Stikini Ring +1",
    left_ring="Purity Ring",
    left_ring="Hetairoi Ring",
    left_ear="Infused Earring",
    sub="Vadose Rod",
    head="Pixie Hairpin +1",
    sub="Daybreak",
    waist="Embla Sash",
    waist="Orpheus's Sash",
    head={ name="Ryuo Somen +1", augments={'HP+65','"Store TP"+5','"Subtle Blow"+8',}},
    feet={ name="Tatena. Sune. +1", augments={'Path: A',}},
    feet="Helios Boots",
    hands="Helios Gloves",
    ammo="Aurgelmir Orb",
    main="Shining One",
    left_ring="Stikini Ring +1",
    left_ring="Chirich Ring +1",
    left_ring="Eshmun's Ring",
    body={ name="Herculean Vest", augments={'Mag. Acc.+29','"Mag.Atk.Bns."+18','"Treasure Hunter"+2','Accuracy+4 Attack+4','Mag. Acc.+20 "Mag.Atk.Bns."+20',}},
    head={ name="Herculean Helm", augments={'"Fast Cast"+6','Mag. Acc.+13','"Mag.Atk.Bns."+2',}},
    head={ name="Herculean Helm", augments={'STR+8','Weapon Skill Acc.+15','"Refresh"+1','Mag. Acc.+17 "Mag.Atk.Bns."+17',}},
    left_ear="Vor Earring",
    ammo={ name="Seeth. Bomblet +1", augments={'Path: A',}},
    hands="Malignance Gloves",
    ammo="Knobkierrie",
    body="Hjarrandi Breast.",
    neck="Anu Torque",
    left_ring="Petrov Ring",
    head="Hjarrandi Helm",
    feet="Sulev. Leggings +2",
    legs="Sulev. Cuisses +2",
    feet="Flam. Gambieras +2",
    head="Flam. Zucchetto +2",
    left_ring="Epaminondas's Ring",
    ammo={ name="Coiste Bodhar", augments={'Path: A',}},
    hands="Sulev. Gauntlets +2",
    head={ name="Blistering Sallet +1", augments={'Path: A',}},
    left_ring="Niqmaddu Ring",
    sub="Utu Grip",
    body={ name="Gleti's Cuirass", augments={'Path: A',}},
    feet="Ostro Greaves",
    feet={ name="Ptero. Greaves +1", augments={'Enhances "Empathy" effect',}},
    neck={ name="Dgn. Collar +2", augments={'Path: A',}},
    ammo="Angon",
    ammo="Crepuscular Pebble",
    body={ name="Acro Surcoat", augments={'Pet: Breath+8',}},
    legs={ name="Ptero. Brais +3", augments={'Enhances "Strafe" effect',}},
    hands={ name="Acro Gauntlets", augments={'Accuracy+20 Attack+20','"Store TP"+6','STR+5 DEX+5',}},
    hands={ name="Acro Gauntlets", augments={'Pet: Breath+8',}},
    hands="Vishap F. G. +1",
    back={ name="Updraft Mantle", augments={'STR+2','Pet: Breath+10','Pet: Damage taken -3%',}},
    back={ name="Brigantia's Mantle", augments={'STR+20','Accuracy+20 Attack+20','"Dbl.Atk."+10','Damage taken-5%',}},
    back={ name="Brigantia's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
    hands={ name="Ptero. Fin. G. +3", augments={'Enhances "Angon" effect',}},
    head={ name="Ptero. Armet +3", augments={'Enhances "Deep Breathing" effect',}},
    body={ name="Ptero. Mail +1", augments={'Enhances "Spirit Surge" effect',}},
    left_ear="Anastasi Earring",
    legs="Vishap Brais +1",
    range={ name="Dunna", augments={'MP+20','Mag. Acc.+10','"Fast Cast"+3',}},
    left_ring="Luzaf's Ring",
    left_ear="Kuwunga Earring",
    hands="Bunzi's Gloves",
    sub={ name="Kunimitsu", augments={'Path: A',}},
    waist="Windbuffet Belt +1",
    body="Hiza. Haramaki +2",
    back="Tempered Cape +1",
    body="Pinga Tunic +1",
    ammo="Barathrum",
    ammo="Yamarang",
    range={ name="Linos", augments={'Accuracy+14 Attack+14','Weapon skill damage +3%','Quadruple Attack +3',}},
    head="Hachiya Hatsu. +3",
    head={ name="Mochi. Hatsuburi +3", augments={'Enhances "Yonin" and "Innin" effect',}},
    head="Malignance Chapeau",
    left_ring="Sheltered Ring",
    waist="Witful Belt",
    back="Grapevine Cape",
    left_ring="Fenrir Ring +1",
    head="Midras's Helm +1",
    body={ name="Piety Bliaut +3", augments={'Enhances "Benediction" effect',}},
    body={ name="Mochi. Chainmail +3", augments={'Enhances "Sange" effect',}},
    left_ear="Earthcry Earring",
    waist="Flume Belt +1",
    neck="Quanpur Necklace",
    ammo="Impatiens",
    left_ear="Enchntr. Earring +1",
    left_ring="Shiva Ring +1",
    left_ear="Friomisi Earring",
    ammo="Staunch Tathlum +1",
    waist="Emphatikos Rope",
    feet="Hashi. Basmak +3",
    body="Hashishin Mintan +3",
    range="Marsyas",
    head="Jhakri Coronal +2",
    head="Ebers Cap +3",
    back={ name="Rosmerta's Cape", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
    head={ name="Luh. Keffiyeh +1", augments={'Enhances "Convergence" effect',}},
    feet="Hattori Kyahan +3",
    waist="Cimmerian Sash",
    back={ name="Camulus's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','"Store TP"+10','Damage taken-5%',}},
    sub="Gandring",
    hands="Assim. Bazu. +1",
    back={ name="Intarabus's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dual Wield"+10','Phys. dmg. taken-10%',}},
    sub="Beneficus",
    legs="Darraigner's Brais",
    body="Hattori Ningi +3",
    back={ name="Intarabus's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Store TP"+10','Phys. dmg. taken-10%',}},
    sub={ name="Kali", augments={'MP+60','Mag. Acc.+20','"Refresh"+1',}},
    hands="Fili Manchettes +2",
    hands="Theophany Mitts +3",
    hands="Brioso Cuffs +3",
    legs="Hattori Hakama +1",
    back={ name="Rosmerta's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
    back={ name="Rosmerta's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','Magic Damage +10','"Mag.Atk.Bns."+10',}},
    body="Ebers Bliaut +3",
    legs="Hashishin Tayt +3",
    legs="Fili Rhingrave +1",
    feet="Brioso Slippers +3",
    head="Halitus Helm",
    left_ear={ name="Pel. Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+14','Mag. Acc.+14','Crit.hit rate+5',}},
    waist="Fucho-no-Obi",
    feet={ name="Bunzi's Sabots", augments={'Path: A',}},
    feet={ name="Luhlaza Charuqs +1", augments={'Enhances "Diffusion" effect',}},
    feet={ name="Piety Duckbills +1", augments={'Enhances "Afflatus Solace" effect',}},
    body={ name="Telchine Chas.", augments={'Enh. Mag. eff. dur. +10',}},
    feet="Ebers Duckbills +3",
    body="Emet Harness +1",
    feet={ name="Telchine Pigaches", augments={'Enh. Mag. eff. dur. +10',}},
    feet="Theo. Duckbills +1",
    neck="Rep. Plat. Medal",
    range="Earp",
    legs={ name="Telchine Braconi", augments={'Enh. Mag. eff. dur. +10',}},
    waist="Rumination Sash",
    left_ear={ name="Chas. Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+12','Mag. Acc.+12','Crit.hit rate+4',}},
    neck={ name="Clr. Torque +2", augments={'Path: A',}},
    neck={ name="Ninja Nodowa +2", augments={'Path: A',}},
    head={ name="Telchine Cap", augments={'Enh. Mag. eff. dur. +10',}},
    left_ear="Njordr Earring",
    hands={ name="Telchine Gloves", augments={'Enh. Mag. eff. dur. +10',}},
    main={ name="Grioavolr", augments={'"Fast Cast"+7','"Mag.Atk.Bns."+8',}},
    back={ name="Alaunus's Cape", augments={'MND+20','Eva.+20 /Mag. Eva.+20','"Cure" potency +10%','Phys. dmg. taken-10%',}},
    neck={ name="Mirage Stole +2", augments={'Path: A',}},
    hands={ name="Luh. Bazubands +1", augments={'Enhances "Azure Lore" effect',}},
    back={ name="Mecisto. Mantle", augments={'Cap. Point+40%','DEF+7',}},
    back="Bane Cape",
    hands="Ebers Mitts +3",
    feet="Assim. Charuqs +1",
    body={ name="Luhlaza Jubbah +1", augments={'Enhances "Enchainment" effect',}},
    ammo="Mavi Tathlum",
    range="Gjallarhorn",
    range="Daurdabla",
    legs={ name="Bihu Cannions", augments={'Enhances "Soul Voice" effect',}},
    feet="Fili Cothurnes +1",
    back={ name="Intarabus's Cape", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
    back={ name="Intarabus's Cape", augments={'CHR+20','Mag. Acc+20 /Mag. Dmg.+20','Mag. Acc.+10','"Fast Cast"+10','Mag. Evasion+15',}},
    hands={ name="Floral Gauntlets", augments={'Rng.Acc.+13','Accuracy+14','"Triple Atk."+1','Magic dmg. taken -2%',}},
    head={ name="Chironic Hat", augments={'Pet: INT+6','Pet: STR+1','"Treasure Hunter"+1','Accuracy+20 Attack+20','Mag. Acc.+4 "Mag.Atk.Bns."+4',}},
    sub="Carnwenhan",
    legs="Th. Pantaloons +2",
    head="Fili Calot +1",
    head={ name="Piety Cap +1", augments={'Enhances "Devotion" effect',}},
    sub="Yagrush",
    legs={ name="Piety Pantaln. +3", augments={'Enhances "Afflatus Misery" effect',}},
    body="Twilight Cloak",
    body="Fili Hongreline +1",
    waist={ name="Obstin. Sash", augments={'Path: A',}},
    neck="Nicander's Necklace",
    feet="Pill. Poulaines +1",
    legs="Ebers Pant. +3",
    sub="Genmei Shield",
    head="Hashishin Kavuk +3",
    sub="Gandring",
    body="Jhakri Robe +2",
    body="Pillager's Vest +1",
    body="Laksa. Frac +3",
    hands={ name="Plun. Armlets +3", augments={'Enhances "Perfect Dodge" effect',}},
    body="Assim. Jubbah +2",
    left_ear="Stealth Earring",
    legs="Jhakri Slops +2",
    hands="Hattori Tekko +1",
    sub="Agwu's Axe",
    hands="Hashi. Bazu. +3",
    hands="Pill. Armlets +1",
    legs={ name="Luhlaza Shalwar +3", augments={'Enhances "Assimilation" effect',}},
    legs="Pill. Culottes +1",
    head="Pill. Bonnet +1",
    feet="Jute Boots +1",
    legs="Zoar Subligar +1",
    legs="Assim. Shalwar +1",
    feet="Jhakri Pigaches +2",
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dbl.Atk."+10',}},
    neck={ name="Vim Torque +1", augments={'Path: A',}},
    feet="Skulk. Poulaines +1",
    feet={ name="Odyssean Greaves", augments={'Pet: Attack+15 Pet: Rng.Atk.+15','DEX+8','Phalanx +4','Accuracy+4 Attack+4',}},
    feet="Danzo Sune-Ate",
    back={ name="Andartia's Mantle", augments={'AGI+20','Accuracy+20 Attack+20','AGI+10','Weapon skill damage +10%',}},
    ammo="Seki Shuriken",
    back={ name="Andartia's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
    feet={ name="Mochi. Kyahan +3", augments={'Enh. Ninj. Mag. Acc/Cast Time Red.',}},
    legs={ name="Mochi. Hakama +3", augments={'Enhances "Mijin Gakure" effect',}},
    sub={ name="Hitaki", augments={'TP Bonus +1000',}},
    sub={ name="Fudo Masamune", augments={'Path: A',}},
    left_ear={ name="Hattori Earring +2", augments={'System: 1 ID: 1676 Val: 0','Accuracy+18','Mag. Acc.+18','"Store TP"+7','DEX+11 AGI+11',}},
    head="Ken. Jinpachi +1",
    feet="Chass. Bottes +3",
    neck="Regal Necklace",
    back="Pastoralist's Mantle",
    body={ name="Lanun Frac +3", augments={'Enhances "Loaded Deck" effect',}},
    legs={ name="Lanun Trews +1", augments={'Enhances "Snake Eye" effect',}},
    feet={ name="Lanun Bottes +3", augments={'Enhances "Wild Card" effect',}},
    hands={ name="Agwu's Gages", augments={'Path: A',}},
    left_ring="Rahab Ring",
    left_ear="Genmei Earring",
    range="Death Penalty",
    back={ name="Camulus's Mantle", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','"Store TP"+10','Phys. dmg. taken-10%',}},
    back={ name="Camulus's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%','Mag. Evasion+15',}},
    feet={ name="Agwu's Pigaches", augments={'Path: A',}},
    back={ name="Camulus's Mantle", augments={'INT+20','Eva.+20 /Mag. Eva.+20','"Snapshot"+10','Mag. Evasion+15',}},
    back={ name="Camulus's Mantle", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','Weapon skill damage +10%',}},
    back={ name="Camulus's Mantle", augments={'AGI+20','Mag. Acc+20 /Mag. Dmg.+20','AGI+10','Weapon skill damage +10%','Mag. Evasion+15',}},
    hands="Chasseur's Gants +3",
    hands={ name="Lanun Gants +3", augments={'Enhances "Fold" effect',}},
    legs={ name="Adhemar Kecks +1", augments={'AGI+12','"Rapid Shot"+13','Enmity-6',}},
    neck="Sanctity Necklace",
    hands={ name="Carmine Fin. Ga. +1", augments={'Rng.Atk.+20','"Mag.Atk.Bns."+12','"Store TP"+6',}},
    feet={ name="Adhe. Gamashes +1", augments={'HP+65','"Store TP"+7','"Snapshot"+10',}},
    body="Chasseur's Frac +3",
    legs="Chas. Culottes +3",
    legs="Ken. Hakama +1",
    main={ name="Aettir", augments={'Accuracy+70','Mag. Evasion+50','Weapon skill damage +10%',}},
    waist="Yemaya Belt",
    sub={ name="Lanun Knife", augments={'Path: A',}},
    feet={ name="Pursuer's Gaiters", augments={'Rng.Acc.+10','"Rapid Shot"+10','"Recycle"+15',}},
    feet="Malignance Boots",
    feet="Laksa. Bottes +2",
    feet="Ken. Sune-Ate +1",
    head="Laksa. Tricorne +3",
    hands="Laksa. Gants +1",
    range={ name="Compensator", augments={'DMG:+15','AGI+15','Rng.Acc.+15',}},
    left_ear="Beyla Earring",
    legs="Laksa. Trews",
    range={ name="Anarchy +2", augments={'Delay:+60','TP Bonus +1000',}},
    left_ear="Enervating Earring",
    neck="Iskur Gorget",
    head={ name="Lanun Tricorne +3", augments={'Enhances "Winning Streak" effect',}},
    waist="Reiki Yotai",
    feet="Hiza. Sune-Ate +2",
    legs="Jokushu Haidate",
    sub="Thunder Hammer",
    main="Zanmato",
    back="Nexus Cape",
    legs="Enif Cosciales",
    left_ear="Digni. Earring",
    sub="Colada",
    main="Goujian",
    sub="Twinned Blade",
    sub="Wind Knife",
    sub="Kunai",
    main="Iapetus",
    main="Hoe",
    back="Perimede Cape",
    body={ name="Taeon Tabard", augments={'"Fast Cast"+5','Phalanx +3',}},
    neck="Sibyl Scarf",
    left_ring="Echad Ring",
    hands={ name="Taeon Gloves", augments={'Phalanx +3',}},
    feet={ name="Taeon Boots", augments={'Phalanx +3',}},
    head={ name="Taeon Chapeau", augments={'Phalanx +3',}},
    legs={ name="Taeon Tights", augments={'Phalanx +3',}},
    head={ name="Ikenga's Hat", augments={'Path: A',}},
    head={ name="Mpaca's Cap", augments={'Path: A',}},
    body={ name="Ikenga's Vest", augments={'Path: A',}},
    hands={ name="Gleti's Gauntlets", augments={'Path: A',}},
    left_ear="Tuisto Earring",
    left_ring={ name="Gelatinous Ring +1", augments={'Path: A',}},
    sub={ name="Gleti's Knife", augments={'Path: A',}},
    left_ring="Rajas Ring",
    neck="Elite Royal Collar",
    sub="Mafic Cudgel",
    left_ring="Supershear Ring",
    sub="Balarama Grip",
    left_ear={ name="Odnowa Earring +1", augments={'Path: A',}},
    sub="Sakpata's Sword",
    neck={ name="Unmoving Collar +1", augments={'Path: A',}},
    left_ring="Vexer Ring +1",
    left_ear="Reraise Earring",
    left_ear={ name="Nukumi Earring", augments={'System: 1 ID: 1676 Val: 0','Accuracy+10','Mag. Acc.+10',}},
    hands={ name="Macabre Gaunt. +1", augments={'Path: A',}},
    left_ear="Cryptic Earring",
    neck="Adad Amulet",
    head={ name="Rawhide Mask", augments={'HP+50','Accuracy+15','Evasion+20',}},
    left_ring="Warp Ring",
    sub="Dokoku",
    ammo="Dire Broth",
    sub="Bolelabunga",
    sub="Wind Knife",
    main="Sophistry",
    sub="Gokotai",
    left_ring="Asklepian Ring",
    left_ring="Prolix Ring",
    body={ name="Peda. Gown +3", augments={'Enhances "Enlightenment" effect',}},
    back={ name="Bookworm's Cape", augments={'INT+5','MND+2','Helix eff. dur. +20','"Regen" potency+10',}},
    left_ear="Andoaa Earring",
    head="Brioso Roundlet +3",
    feet={ name="Helios Boots", augments={'Mag. Acc.+19 "Mag.Atk.Bns."+19','"Occult Acumen"+9','INT+9',}},
    head={ name="Peda. M.Board +3", augments={'Enh. "Altruism" and "Focalization"',}},
    legs="Arbatel Pants +3",
    head="Arbatel Bonnet +3",
    left_ear={ name="Arbatel Earring", augments={'System: 1 ID: 1676 Val: 0','Mag. Acc.+6',}},
    left_ear="Mani Earring",
    neck="Stone Gorget",
    neck="Moonlight Necklace",
    left_ring="Locus Ring",
    left_ring="Cornelia's Ring",
    head="Agwu's Cap",
    left_ear="Gifted Earring",
    back="Solemnity Cape",
    body="Vedic Coat",
    hands="Acad. Bracers +2",
    body="Arbatel Gown +3",
    left_ear="Hirudinea Earring",
    feet="Ahosi Leggings",
    feet={ name="Peda. Loafers +3", augments={'Enhances "Stormsurge" effect',}},
    hands={ name="Merlinic Dastanas", augments={'Mag. Acc.+4 "Mag.Atk.Bns."+4','"Drain" and "Aspir" potency +11','MND+9','Mag. Acc.+4','"Mag.Atk.Bns."+1',}},
    hands={ name="Peda. Bracers +3", augments={'Enh. "Tranquility" and "Equanimity"',}},
    left_ear="Gersemi Earring",
    legs={ name="Peda. Pants +3", augments={'Enhances "Tabula Rasa" effect',}},
    legs="Brioso Cannions +3",
    feet={ name="Bihu Slippers +3", augments={'Enhances "Nightingale" effect',}},
    body="Brioso Justau. +3",
    left_ear={ name="Fili Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+11','Mag. Acc.+11','Damage taken-3%',}},
    waist={ name="Acuity Belt +1", augments={'Path: A',}},
    legs="Gyve Trousers",
    sub="Khonsu",
    back={ name="Lugh's Cape", augments={'MP+60','Eva.+20 /Mag. Eva.+20','"Fast Cast"+10',}},
    feet="Acad. Loafers +2",
    head="Acad. Mortar. +2",
    back={ name="Lugh's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','"Mag.Atk.Bns."+10','Damage taken-5%',}},
    hands="Hieros Mittens",
    head={ name="Merlinic Hood", augments={'Mag. Acc.+23','"Fast Cast"+6','MND+6','"Mag.Atk.Bns."+15',}},
    hands={ name="Helios Gloves", augments={'"Mag.Atk.Bns."+23','"Occult Acumen"+10','INT+10',}},
    head="Chass. Tricorne +2",
    neck="Erra Pendant",
    feet={ name="Merlinic Crackows", augments={'"Fast Cast"+7','Mag. Acc.+7',}},
    feet={ name="Merlinic Crackows", augments={'Mag. Acc.+18 "Mag.Atk.Bns."+18','"Conserve MP"+7','MND+5','Mag. Acc.+11',}},
    hands="Arbatel Bracers +3",
    left_ear="Enmerkar Earring",
    waist="Incarnation Sash",
    main={ name="Musa", augments={'Path: C',}},
    hands={ name="Leyline Gloves", augments={'Accuracy+15','Mag. Acc.+15','"Mag.Atk.Bns."+15','"Fast Cast"+3',}},
    hands={ name="Fanatic Gloves", augments={'MP+50','Healing magic skill +10','"Conserve MP"+7','"Fast Cast"+7',}},
    feet={ name="Medium's Sabots", augments={'MP+45','MND+9','"Conserve MP"+5','"Cure" potency +4%',}},
    left_ear={ name="Chas. Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+11','Mag. Acc.+11','Crit.hit rate+3',}},
    legs={ name="Samnuha Tights", augments={'STR+10','DEX+10','"Dbl.Atk."+3','"Triple Atk."+3',}},
    neck={ name="Comm. Charm +2", augments={'Path: A',}},
    neck={ name="Bard's Charm +2", augments={'Path: A',}},
    sub="Nusku Shield",
    body={ name="Agony Jerkin +1", augments={'Path: A',}},
    sub={ name="Malevolence", augments={'INT+10','Mag. Acc.+10','"Mag.Atk.Bns."+10','"Fast Cast"+5',}},
    feet="Arbatel Loafers +3",
    left_ear={ name="Boii Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+15','Mag. Acc.+15','Crit.hit rate+5',}},
    body={ name="Bihu Jstcorps. +3", augments={'Enhances "Troubadour" effect',}},
    sub="Heishi Shorinken",
    legs={ name="Agwu's Slops", augments={'Path: A',}},
    sub={ name="Rubicundity", augments={'Mag. Acc.+5','"Mag.Atk.Bns."+3','Dark magic skill +8',}},
    sub={ name="Rostam", augments={'Path: C',}},
    sub={ name="Kustawi +1", augments={'Path: A',}},
    neck={ name="Argute Stole +2", augments={'Path: A',}},
    item="Wisteria Lumber",
    item="Land Crab Meat",
    item="Hare Meat",
    item="Rabbit Hide",
    item="Boyahda Moss",
    item="Insect Wing",
    item="Wind Crystal",
    item="Earth Crystal",
    item="Water Crystal",
    item="Byd. Coffer Key",
}